import { Model } from "mongoose";
import { AllSchemas } from "./models";

/**
 * The representation of a data resource or software resource to help the connector
 * pull the data from the owner's data application
 **/
export interface IRepresentation {
  /**
   * ID of the data resource
   */
  resourceID: string;

  /**
   * URL of the API to call for the connector to
   * GET the data from the owner's data application
   */
  url: string;

  /**
   * Credential used for the API call to the specified url.
   * The credential is generated by the connector and represented
   * here by an id only the connector knows to correlate the actual
   * credentials inside its database.
   */
  credential: string;
}

export interface IRepresentationMethods {}

export interface IRepresentationModel
  extends Model<IRepresentation, object, IRepresentationMethods> {}
